version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2
   
    working_directory: ~/app

    steps:
      - checkout:
          git:
            url: "https://github.com/SlavomirL/CrosswordSolver.git" 

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew.bat dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Run Gradle build and tests
          command: ./gradlew.bat build --no-daemon

workflows:
  version: 2
  build:
    jobs:
      - build
